# Generated by Django 5.1.4 on 2025-01-19 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="名前"
                    ),
                ),
                (
                    "mail",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="配信用メールアドレス",
                    ),
                ),
                (
                    "post",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "phone1",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="電話番号"
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="保護者の電話番号",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="投稿日時"
                    ),
                ),
                (
                    "manageruser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="マネージャー",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.IntegerField(blank=True, null=True, verbose_name="教育段階"),
                ),
                (
                    "grade",
                    models.IntegerField(blank=True, null=True, verbose_name="学年"),
                ),
                (
                    "schoolclass",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="組"
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="学校名"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="投稿日時"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.student",
                        verbose_name="生徒",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="科目名"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="投稿日時"
                    ),
                ),
                (
                    "manageruser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="マネージャー",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="投稿日時"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.student",
                        verbose_name="生徒",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.subject",
                        verbose_name="科目",
                    ),
                ),
            ],
        ),
    ]
