# Generated by Django 5.1.4 on 2025-01-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentschool",
            name="stage",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="教育段階"
            ),
        ),
    ]
