# Generated by Django 5.1.4 on 2025-01-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0003_alter_studentschool_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentschool",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, to="classmanager.subject", verbose_name="科目"
            ),
        ),
    ]
