# Generated by Django 5.1.4 on 2025-01-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0004_studentschool_subjects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentschool",
            name="subjects",
        ),
    ]
