# Generated by Django 5.1.4 on 2025-01-28 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0006_schoolsubject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="名前"
                    ),
                ),
                (
                    "mail",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="メールアドレス",
                    ),
                ),
                (
                    "post",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "phone1",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="電話番号"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="メモ"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="投稿日時"
                    ),
                ),
                (
                    "manageruser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="マネージャー",
                    ),
                ),
            ],
        ),
    ]
