# Generated by Django 5.1.4 on 2025-01-29 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0007_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="開始時間")),
                ("end_time", models.DateTimeField(verbose_name="終了時間")),
                ("location", models.CharField(max_length=200, verbose_name="場所")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.student",
                        verbose_name="生徒",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.subject",
                        verbose_name="科目",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.teacher",
                        verbose_name="教師",
                    ),
                ),
            ],
        ),
    ]
