# Generated by Django 5.1.4 on 2025-01-29 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountsclassroom", "0001_initial"),
        ("classmanager", "0008_classschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classschedule",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="location",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="subject",
        ),
        migrations.AddField(
            model_name="classschedule",
            name="classroomuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountsclassroom.classroomuser",
                verbose_name="教室",
            ),
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="タイトル"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了時間"
                    ),
                ),
                (
                    "manageruser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="マネージャー",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classschedule",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classmanager.period",
                verbose_name="時限",
            ),
        ),
        migrations.DeleteModel(
            name="StudentSubject",
        ),
    ]
