# Generated by Django 5.1.4 on 2025-01-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0009_remove_classschedule_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="日付"),
        ),
    ]
