# Generated by Django 5.1.4 on 2025-01-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0010_classschedule_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="終了時間"),
        ),
        migrations.AlterField(
            model_name="period",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="開始時間"),
        ),
    ]
