# Generated by Django 5.1.4 on 2025-01-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountsclassroom", "0001_initial"),
        ("classmanager", "0011_alter_period_end_time_alter_period_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="classroomuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountsclassroom.classroomuser",
                verbose_name="教室",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="classroomuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountsclassroom.classroomuser",
                verbose_name="教室",
            ),
        ),
    ]
