# Generated by Django 5.1.4 on 2025-02-02 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountsclassroom", "0001_initial"),
        ("classmanager", "0012_student_classroomuser_teacher_classroomuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="attendance",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="出席"
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="behindtime",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="遅刻"
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="earlytime",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="早退"
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="homework",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="次の宿題"
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="managermessage",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="マネージャーメッセージ",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="nextlesson",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="次の授業"
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="parentsmessage",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="保護者へのメッセージ",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="poster",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="姿勢"
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="teachermessage",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="教師メッセージ"
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="understand",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="理解"
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag", models.BooleanField(default=True)),
                (
                    "behindtime",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="遅刻"
                    ),
                ),
                (
                    "earlytime",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="早退"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="日付")),
                (
                    "classroomuser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountsclassroom.classroomuser",
                        verbose_name="教室",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.period",
                        verbose_name="時限",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.student",
                        verbose_name="生徒",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.teacher",
                        verbose_name="教師",
                    ),
                ),
            ],
        ),
    ]
