# Generated by Django 5.1.4 on 2025-02-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classmanager",
            "0013_classschedule_attendance_classschedule_behindtime_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classschedule",
            name="attendance",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="behindtime",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="earlytime",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="homework",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="managermessage",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="nextlesson",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="parentsmessage",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="poster",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="teachermessage",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="understand",
        ),
        migrations.RemoveField(
            model_name="report",
            name="period",
        ),
        migrations.AddField(
            model_name="report",
            name="attendance",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="出席"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="homework",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="次の宿題"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="managermessage",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="マネージャーメッセージ",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="nextlesson",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="次の授業"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="parentsmessage",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="保護者へのメッセージ",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="poster",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="姿勢"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="teachermessage",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="教師メッセージ"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="understand",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="理解"
            ),
        ),
    ]
