# Generated by Django 5.1.4 on 2025-02-02 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0014_remove_classschedule_attendance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classmanager.period",
                verbose_name="時限",
            ),
        ),
    ]
