# Generated by Django 5.1.4 on 2025-02-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0015_report_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="posted_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="投稿日時"
            ),
        ),
    ]
