# Generated by Django 5.1.4 on 2025-02-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0016_report_posted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="flag",
            field=models.BooleanField(default=True),
        ),
    ]
