# Generated by Django 5.1.4 on 2025-02-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0017_classschedule_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="achievement",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="達成度"
            ),
        ),
    ]
