# Generated by Django 5.1.4 on 2025-02-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0018_report_achievement"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="学校名"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="教育段階"
                    ),
                ),
            ],
        ),
    ]
