# Generated by Django 5.1.4 on 2025-02-18 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0023_alter_studentschool_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentschool",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classmanager.school",
                verbose_name="学校",
            ),
        ),
    ]
