# Generated by Django 5.1.4 on 2025-02-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0025_remove_studentschool_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentschool",
            name="school",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="学校名"
            ),
        ),
    ]
