# Generated by Django 5.1.4 on 2025-02-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0026_studentschool_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentschool",
            name="school",
        ),
    ]
