# Generated by Django 5.1.4 on 2025-02-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0028_studentschool_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="phone1",
        ),
        migrations.RemoveField(
            model_name="student",
            name="phone2",
        ),
    ]
