# Generated by Django 5.1.4 on 2025-02-18 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0029_remove_student_phone1_remove_student_phone2"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="名前"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.student",
                        verbose_name="生徒",
                    ),
                ),
            ],
        ),
    ]
