# Generated by Django 5.1.4 on 2025-02-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0030_studentphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentphone",
            name="text",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="メモ"
            ),
        ),
    ]
