# Generated by Django 5.1.4 on 2025-02-25 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0035_category_manageruser_englishwords_manageruser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userenglishwords",
            name="category",
        ),
        migrations.RemoveField(
            model_name="userenglishwords",
            name="manageruser",
        ),
        migrations.RemoveField(
            model_name="userparentcategory",
            name="manageruser",
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="EnglishScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="翻訳"
                    ),
                ),
                (
                    "cleartime",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="翻訳"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="投稿日時"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classmanager.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.student",
                        verbose_name="生徒",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserCategory",
        ),
        migrations.DeleteModel(
            name="UserEnglishWords",
        ),
        migrations.DeleteModel(
            name="UserParentCategory",
        ),
    ]
