# Generated by Django 5.1.4 on 2025-02-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0036_remove_userenglishwords_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="englishscore",
            name="score",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="スコア"
            ),
        ),
    ]
