# Generated by Django 5.1.4 on 2025-02-26 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0037_alter_englishscore_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnglishGameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="スコア")),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.student",
                        verbose_name="生徒",
                    ),
                ),
            ],
        ),
    ]
