# Generated by Django 5.1.4 on 2025-03-01 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0038_englishgamesession"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransGameScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="スコア"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="投稿日時"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classmanager.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classmanager.student",
                        verbose_name="生徒",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EnglishGameSession",
        ),
    ]
