# Generated by Django 5.1.4 on 2025-03-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classmanager", "0039_transgamescore_delete_englishgamesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="transgamescore",
            name="cleartime",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="翻訳"
            ),
        ),
    ]
