# Generated by Django 5.1.4 on 2025-01-19 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("accountsclassroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerclassroom",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountsclassroom.classroomuser",
                verbose_name="教室",
            ),
        ),
        migrations.AddField(
            model_name="managerclassroom",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="マネージャー",
            ),
        ),
    ]
