# Generated by Django 5.1.4 on 2025-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageruser",
            name="send_email_address",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="配信元メールアドレス",
            ),
        ),
    ]
