# Generated by Django 5.1.4 on 2025-02-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_manageruser_send_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageruser",
            name="email_setting",
            field=models.BooleanField(default=True),
        ),
    ]
